name: CI/CD

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: '1.21.x'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          
      - name: Install dependencies
        run: go mod download
        
      - name: Verify dependencies
        run: go mod verify
        
      - name: Run tests
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt

  build:
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          
      - name: Install gox
        run: go install github.com/mitchellh/gox@latest
        
      - name: Build binaries
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          gox -osarch="windows/amd64 linux/amd64 darwin/amd64" \
              -ldflags="-X main.version=$VERSION" \
              -output="bin/baxfer_{{.OS}}_{{.Arch}}{{if eq .OS \"windows\"}}.exe{{end}}" \
              ./cmd/baxfer
              
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/baxfer_windows_amd64.exe
            bin/baxfer_linux_amd64
            bin/baxfer_darwin_amd64
          prerelease: ${{ contains(github.ref, '-alpha.') || contains(github.ref, '-beta.') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}